"""Self-hosts the site's Google Fonts: downloads woff2 subsets into assets/fonts and writes assets/css/fonts.css.

Run from the repo root:  python tools/fetch-fonts.py
Only the latin, latin-ext, cyrillic (RU) and armenian (HY) subsets are kept; the Noto Armenian
fonts only need their armenian subset, since Inter / Cormorant cover latin and cyrillic first.
"""
import collections, os, re, urllib.request

FAMILIES = ('family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300&family=Inter:wght@300;400;500'
            '&family=Noto+Sans+Armenian:wght@300;400;500&family=Noto+Serif+Armenian:wght@300;400&display=swap')
SUBSETS = {'Cormorant Garamond': {'latin', 'latin-ext', 'cyrillic'}, 'Inter': {'latin', 'latin-ext', 'cyrillic'},
           'Noto Sans Armenian': {'armenian'}, 'Noto Serif Armenian': {'armenian'}}
SLUG = {'Cormorant Garamond': 'cormorant', 'Inter': 'inter', 'Noto Sans Armenian': 'noto-sans-armenian', 'Noto Serif Armenian': 'noto-serif-armenian'}
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'  # → woff2

req = urllib.request.Request('https://fonts.googleapis.com/css2?' + FAMILIES, headers={'User-Agent': UA})
css = urllib.request.urlopen(req).read().decode()
faces = collections.OrderedDict()
for sub, body in re.findall(r'/\* ([a-z-]+) \*/\s*@font-face \{(.*?)\}', css, re.S):
    fam = re.search(r"font-family: '([^']+)'", body)[1]
    if sub not in SUBSETS[fam]:
        continue
    style = re.search(r'font-style: (\w+)', body)[1]
    url = re.search(r'url\(([^)]+)\)', body)[1]
    face = faces.setdefault((fam, style, sub, url), {'w': set(), 'range': re.search(r'unicode-range: ([^;]+);', body)[1]})
    face['w'].add(int(re.search(r'font-weight: (\d+)', body)[1]))

os.makedirs('assets/fonts', exist_ok=True)
out = ['/* Self-hosted fonts (SIL OFL), generated by tools/fetch-fonts.py */']
for (fam, style, sub, url), f in faces.items():
    name = f"{SLUG[fam]}{'-italic' if style == 'italic' else ''}-{sub}.woff2"
    urllib.request.urlretrieve(url, 'assets/fonts/' + name)
    w = sorted(f['w'])
    weight = str(w[0]) if len(w) == 1 else f'{w[0]} {w[-1]}'
    out.append(f"@font-face{{font-family:'{fam}';font-style:{style};font-weight:{weight};font-display:swap;"
               f"src:url(../fonts/{name}) format('woff2');unicode-range:{f['range']}}}")
    print(name)
with open('assets/css/fonts.css', 'w') as fh:
    fh.write('\n'.join(out) + '\n')
